### ISSUE TITLE
implement map-sort

### ISSUE THREAD

**Issue by lunelson** [lunelson/sass-maps-plus#10]
`map-sort()` was implemented in sass-list-maps as a means to sort a map based on values in sub-maps. It's a bit counterintuitive, probably needs to be rethought to be of more general use.

**Comment by lunelson** [comment]
`map-subsort()` added in commit https://github.com/lunelson/sass-maps-plus/commit/ae63d3dd885176bc55c7767102cfbb037af68dcc

**Comment by lunelson** [comment]
Implemented this; but thinking submap functions could do with a `submap-` name-space, and what else they might do:
- `submap-sort($map, $key)`: sort submaps in a map, based on values at key (needs to be more robust than currently)
- `submap-collect($map, $key)`: output map of submaps, whose value at $key is not falsey
- `submap-collect-has($map, $key)`: output map of submaps, that have key $key
- `submap-collect-equals($map, $key, $value)`: output map of submaps, whose value at $key equals $value
- `submap-reject($map, $key)`: output map of submaps whose value at $key is not falsey
- `submap-reject-has($map, $key)`: output map of submaps that do not contain key $key
- `submap-reject-equals($map, $key, $value)`: output map of submaps, whose value at $key does not equal $value

Not sure if this is logically consistent. Any thoughts @HugoGiraudel or @xzyfer?

**Comment by KittyGiraudel** [comment]
What do you call a _submap_? A map within a map?

**Comment by xzyfer** [comment]
My thoughts exactly. I'm not conceptually sure what a submap is.

**Comment by lunelson** [comment]
I knew something was missing there. Yeah I mean a map within a map-of-maps. Or for that matter a map within a list of maps.
