### ISSUE TITLE
In an attempt to make a map-deep-get() that helpfully errors

### ISSUE THREAD

**Issue by mkstix6** [lunelson/sass-maps-plus#15]
I made this for my project so when I mess up it errors in a slightly helpful way.
I'm super tired so it's probably horrible. But I thought you might like to see it.

```
// utility functions
@function map-deep-get($map, $keys...) {

    $value: $map;
    $keychain: '';
    $finishedallkeys:false;

    @each $key in $keys {
        $keychain: if($keychain == '', $key, $keychain+'.'+$key);

        @if type-of($value) == map{
            @if map-has-key($value, $key) == false{
                @error "map-deep-get(): #{$keychain} doesn't exist in map"
            }
            $value: map-get($value, $key);
        }
        @if type-of($value) != map{
            @if $finishedallkeys == true{
                @error "map-deep-get(): map too shallow; #{$keychain} doesn't exist in map"
            }
            $finishedallkeys: true;
        }
    }
    @return $value;
}
```

**Comment by lunelson** [comment]
@mkstix6 that's nicely done. I think it's a matter of preference, to look to the console for feedback or not. I must admit I don't generally write `@error` handlers in my code, which might be considered poor practice. This implementation simply follows the convention of the built-in `map-get()`, returning `null` if the value is not found (for whatever reason), and I generally structure my code conditionally based on that. 

FWIW, the rest-argument pattern will be adopted in a future version of the native `map-get()`, as confirmed here: https://github.com/sass/sass/issues/1739#issuecomment-122435753
