### ISSUE TITLE
Make compatible with sass eyeglass

### ISSUE THREAD

**Issue by strarsis** [lunelson/sass-maps-plus#16]
As it is usable with all variants of sass, it would be nice to make this also compatible with sass eyeglass.

**Comment by lunelson** [comment]
Thanks for the suggestion @strarsis but I must admit I haven't figured out yet how eyeglass works. I assume I would have to publish this to npm with some kind of specific package info and directory structure... are you familiar with it?

**Comment by strarsis** [comment]
Correct, you can use the yeoman eyeglass generator: 
https://github.com/sass-eyeglass/generator-eyeglass
