### ISSUE TITLE
Use list-separator instead of comma

### ISSUE THREAD

**Issue by KittyGiraudel** [lunelson/sass-maps-plus#5]
I think it would be better to keep the original separator using `list-separator($list)` rather than enforcing `comma`. What do you say?

**Comment by lunelson** [comment]
You're right about this for the `slice()` function, good catch. That would make it more generally consistent and useful.

The other places where I'm forcing comma-separation are specific to 'list-map' functions though, which depend on this for consistency, ("list-maps" must always be comma-separated lists of space-separated pairs).

**Comment by lunelson** [comment]
made `list-separator($list)` the default argument for `slice()` in commit https://github.com/lunelson/sass-maps-plus/commit/ae63d3dd885176bc55c7767102cfbb037af68dcc
