### ISSUE TITLE
Use set-nth when available for list-set-nth

### ISSUE THREAD

**Issue by KittyGiraudel** [lunelson/sass-maps-plus#7]
The `list-set-nth` function could start like this:

``` scss
@function list-set-nth($list, $index, $value) {
  @if function-exists("set-nth") {
    @return set-nth($list, $index, $value);
  }

  // Function core
}
```

**Comment by lunelson** [comment]
Ah yes, I'd forgotten that was there now. In that case maybe I can remove it entirely, given that the compilers to which this applies both have it.

**Comment by KittyGiraudel** [comment]
Even better!

**Comment by lunelson** [comment]
removed `set-nth()` in commit https://github.com/lunelson/sass-maps-plus/commit/ae63d3dd885176bc55c7767102cfbb037af68dcc
