### ISSUE TITLE
Consider using SassDoc

### ISSUE THREAD

**Issue by KittyGiraudel** [lunelson/sass-maps-plus#8]
It would be nice to have a clean API documentation. I would be glad to help with this. :)

**Comment by lunelson** [comment]
Yes it would be nice to have, I never quite got back to it with 'sass-list-maps'—what bothered me was just the block comments in the output. I figured out a gulp workflow (as you know) to strip them out but I didn't finish setting it up. My idea had been to use a commented source file—in this case maybe something like `_sass-maps-plus-doc.scss`—with a build step, to generate the SassDoc files, and to generate a comment-stripped version for end-use (i.e. `_sass-maps-plus.scss`). What do you think?

**Comment by KittyGiraudel** [comment]
Sassdoc now properly supports inline comments. ;)

**Comment by lunelson** [comment]
Oh! Well, then yes.

How best to proceed?

**Comment by KittyGiraudel** [comment]
I can submit a PR with SassDoc comments.

**Comment by lunelson** [comment]
Please do. I'll have to make a project page this time I suppose... how is your site for SassyLists set up? Is it a github project page? Running jekyll or static files?

**Comment by KittyGiraudel** [comment]
We'll use [sassdocify](https://github.com/sassdoc/sassdocify) to run SassDoc on the project and push on the `gh-pages` branch.

Do you allow me to clean the code while I'm at it (line breaks, new lines, spaces...)?

**Comment by lunelson** [comment]
Wow! sassdocify looks great! Yes re: cleaning code, I know you have your preferences ;)

My next task is to write some better tests. Do you do automated testing of any kind on your sass work?
